import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../lib/auth';
import '../styles/admin.css';

interface CandidateLite {
  id: string;
  full_name: string;
}
interface SessionLite {
  id: string;
  partner_center_id: string | null;
  venue: string | null;
  state: string;
}
interface PassRow {
  id: string;
  target_level: string;
  candidate: CandidateLite | null;
  session: SessionLite | null;
}
interface IssuedCert {
  serial: string;
  level: string;
  name: string;
}

type Load = 'loading' | 'ready' | 'error';

function todayLocal(): string {
  const d = new Date();
  const local = new Date(d.getTime() - d.getTimezoneOffset() * 60000);
  return local.toISOString().slice(0, 10);
}

function prettyLevel(s: string): string {
  return s.replace(/_/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase());
}

export default function CertificateIssuance() {
  const { session } = useAuth();
  const me = session?.user?.id ?? null;

  const [rows, setRows] = useState<PassRow[]>([]);
  const [load, setLoad] = useState<Load>('loading');
  const [busyId, setBusyId] = useState<string | null>(null);
  const [rowError, setRowError] = useState<Record<string, string>>({});
  const [issued, setIssued] = useState<IssuedCert[]>([]);

  const fetchPasses = useCallback(async () => {
    setLoad('loading');
    const { data, error } = await supabase
      .from('assessment_results')
      .select(
        'id, target_level, ' +
          'candidate:candidates ( id, full_name ), ' +
          'session:assessment_sessions ( id, partner_center_id, venue, state )',
      )
      .eq('outcome', 'pass')
      .is('certificate_id', null)
      .order('assessed_on', { ascending: true });

    if (error) {
      setLoad('error');
      return;
    }
    setRows((data ?? []) as unknown as PassRow[]);
    setLoad('ready');
  }, []);

  useEffect(() => {
    fetchPasses();
  }, [fetchPasses]);

  async function issue(r: PassRow) {
    if (!r.candidate) return;
    setBusyId(r.id);
    setRowError((m) => {
      const n = { ...m };
      delete n[r.id];
      return n;
    });

    const { data, error } = await supabase
      .from('certificates')
      .insert({
        candidate_id: r.candidate.id,
        candidate_name_snapshot: r.candidate.full_name, // name as printed, snapshotted
        level: r.target_level,
        issued_by_profile_id: me, // self-stamp — required by the examiner insert policy
        partner_center_id: r.session?.partner_center_id ?? null,
        issued_on: todayLocal(),
        // serial is generated by the column default; the trigger links the pass
      })
      .select('serial, level')
      .single();

    setBusyId(null);

    if (error) {
      // The pass-gate trigger raises here if no eligible passing result exists.
      setRowError((m) => ({ ...m, [r.id]: error.message }));
      return;
    }

    // The trigger set this result's certificate_id, so it leaves the queue.
    setRows((list) => list.filter((x) => x.id !== r.id));
    setIssued((list) => [
      { serial: data.serial as string, level: data.level as string, name: r.candidate!.full_name },
      ...list,
    ]);
  }

  return (
    <section className="mas-page">
      <header className="mas-page-head">
        <p className="mas-eyebrow">Issuance</p>
        <h1>Issue certificates</h1>
        <p className="mas-lede">
          Passed candidates awaiting a certificate. Issuing generates a serial and
          makes the certificate publicly verifiable.
        </p>
      </header>

      {issued.length > 0 && (
        <div className="mas-issued">
          {issued.map((c) => (
            <p key={c.serial} className="mas-status mas-status-good">
              Issued {prettyLevel(c.level)} for “{c.name}” —{' '}
              <span className="mas-serial">{c.serial}</span> ·{' '}
              <Link to={`/verify/${c.serial}`}>verify</Link>
            </p>
          ))}
        </div>
      )}

      <div className="mas-admin-toolbar">
        <button
          className="mas-btn-ghost"
          onClick={fetchPasses}
          disabled={load === 'loading'}
        >
          Refresh
        </button>
        {load === 'ready' && (
          <span className="mas-admin-count">{rows.length} awaiting</span>
        )}
      </div>

      {load === 'loading' && <p className="mas-status">Loading…</p>}
      {load === 'error' && (
        <p className="mas-status mas-status-bad">
          Couldn’t load passes. Refresh to try again.
        </p>
      )}
      {load === 'ready' && rows.length === 0 && (
        <p className="mas-status">
          No passed candidates are awaiting a certificate.
        </p>
      )}

      {load === 'ready' && rows.length > 0 && (
        <ul className="mas-admin-list">
          {rows.map((r) => (
            <li key={r.id} className="mas-admin-row">
              <div className="mas-admin-main">
                <h2 className="mas-admin-name">
                  {r.candidate?.full_name ?? 'Candidate'}
                </h2>
                <p className="mas-admin-meta">
                  <span className="mas-pill">{prettyLevel(r.target_level)}</span>
                  <span className="mas-admin-sub">
                    {r.session?.venue || r.session?.state || ''}
                  </span>
                </p>
                {rowError[r.id] && (
                  <p className="mas-status mas-status-bad mas-admin-rowerror">
                    Couldn’t issue: {rowError[r.id]}
                  </p>
                )}
              </div>
              <div className="mas-admin-action">
                <button
                  className="mas-btn-primary"
                  onClick={() => issue(r)}
                  disabled={busyId === r.id}
                >
                  {busyId === r.id ? 'Issuing…' : 'Issue certificate'}
                </button>
              </div>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
