-- ============================================================================
-- Migration: 20260621120000_certificates
-- Phase:     1/2 boundary — certificate ledger + public verification
-- Purpose:   Completes the Phase 1 "verify a certificate by serial" surface,
--            and lays the append-only ledger that Phase 2 issuance writes to.
--
-- Model:
--   * Certificates are APPEND-ONLY and NEVER edited. A hard trigger blocks
--     UPDATE/DELETE outright (defense in depth, beyond RLS).
--   * Corrections use REVOKE-AND-REISSUE: insert a revocation referencing the
--     bad cert (optionally pointing at the replacement), then issue a new cert.
--   * Certs SNAPSHOT the candidate's name at issue, so the record is
--     self-contained and immutable even if the candidate is later anonymized.
--   * Public verification is a FUNCTION keyed by serial (not a view) so the
--     table cannot be enumerated — you can only verify a serial you hold.
--     Anonymized candidates' names are masked in the public result.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Enum — the seven levels, declared 1..7 so the enum sorts as the pathway.
-- ----------------------------------------------------------------------------
create type public.badge_level as enum (
  'starfish',     -- 1
  'sea_turtle',   -- 2
  'guppy',        -- 3
  'octopus',      -- 4
  'frog',         -- 5
  'swordfish',    -- 6
  'dolphin'       -- 7
);


-- ----------------------------------------------------------------------------
-- certificates  (append-only)
-- ----------------------------------------------------------------------------
create table public.certificates (
  id                      uuid              primary key default gen_random_uuid(),
  serial                  text              not null unique,   -- public verification key
  candidate_id            uuid              not null references public.candidates (id) on delete restrict,
  candidate_name_snapshot text              not null,          -- name as printed at issue
  level                   public.badge_level not null,
  issued_by_profile_id    uuid              references public.profiles (id)         on delete set null,
  partner_center_id       uuid              references public.partner_centers (id)  on delete set null,
  issued_on               date              not null default current_date,
  created_at              timestamptz       not null default now()
);

comment on table public.certificates is
  'Append-only certificate ledger. Never edited; corrections via revoke-and-reissue. Names are snapshotted at issue.';
comment on column public.certificates.serial is
  'Public, hard-to-guess verification key. Generated by the issuance flow (Phase 2).';
comment on column public.certificates.candidate_name_snapshot is
  'Name as printed on the certificate at issue. Decoupled from live candidate row to keep the record immutable.';

create index certificates_candidate_idx on public.certificates (candidate_id);
create index certificates_center_idx    on public.certificates (partner_center_id);
create index certificates_level_idx     on public.certificates (level);

-- Hard immutability: block UPDATE/DELETE for everyone (including future loose
-- policies). The only legitimate writes are INSERTs.
create or replace function public.certificates_block_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'certificates are append-only; use revoke-and-reissue'
    using errcode = '0A000';  -- feature_not_supported
end;
$$;

create trigger certificates_no_update
  before update on public.certificates
  for each row execute function public.certificates_block_mutation();

create trigger certificates_no_delete
  before delete on public.certificates
  for each row execute function public.certificates_block_mutation();


-- ----------------------------------------------------------------------------
-- certificate_revocations  (append-only)
--   A certificate is VALID iff no revocation row references it.
--   `replaced_by_certificate_id` links a revoked cert to its reissued successor.
-- ----------------------------------------------------------------------------
create table public.certificate_revocations (
  id                          uuid        primary key default gen_random_uuid(),
  certificate_id              uuid        not null unique references public.certificates (id) on delete restrict,
  replaced_by_certificate_id  uuid        references public.certificates (id)                 on delete restrict,
  revoked_by_profile_id       uuid        references public.profiles (id)                     on delete set null,
  reason                      text,
  revoked_at                  timestamptz not null default now(),
  created_at                  timestamptz not null default now()
);

comment on table public.certificate_revocations is
  'Append-only. One row revokes one certificate (unique). Optional pointer to the reissued replacement.';

create index certificate_revocations_replaced_idx
  on public.certificate_revocations (replaced_by_certificate_id);


-- ----------------------------------------------------------------------------
-- Row Level Security
-- ----------------------------------------------------------------------------
alter table public.certificates             enable row level security;
alter table public.certificate_revocations  enable row level security;

-- certificates: SELECT --------------------------------------------------------
create policy "certificates_select_issuer"
  on public.certificates for select to authenticated
  using ( (select auth.uid()) = issued_by_profile_id );

create policy "certificates_select_center_admin"
  on public.certificates for select to authenticated
  using ( partner_center_id is not null and public.has_role('partner_center_admin', partner_center_id) );

create policy "certificates_select_claimed_parent"
  on public.certificates for select to authenticated
  using ( exists (
    select 1 from public.candidates c
    where c.id = candidate_id
      and c.claimed_by_profile_id = (select auth.uid())
  ) );

create policy "certificates_select_governance"
  on public.certificates for select to authenticated
  using (
    public.has_role('chairperson') or public.has_role('board_member') or public.has_role('chief_examiner')
  );

-- certificates: INSERT --------------------------------------------------------
-- Examiners issue (stamping themselves). Tightening issuance to the examiner's
-- own assessed candidates is Phase 2 (needs the assessment record).
create policy "certificates_insert_examiner"
  on public.certificates for insert to authenticated
  with check ( public.has_role('examiner') and (select auth.uid()) = issued_by_profile_id );

create policy "certificates_insert_governance"
  on public.certificates for insert to authenticated
  with check (
    public.has_role('chairperson') or public.has_role('board_member') or public.has_role('chief_examiner')
  );
-- (No UPDATE/DELETE policies: the immutability trigger blocks those anyway.)

-- revocations: SELECT ---------------------------------------------------------
create policy "revocations_select_revoker"
  on public.certificate_revocations for select to authenticated
  using ( (select auth.uid()) = revoked_by_profile_id );

create policy "revocations_select_claimed_parent"
  on public.certificate_revocations for select to authenticated
  using ( exists (
    select 1
    from public.certificates cert
    join public.candidates cand on cand.id = cert.candidate_id
    where cert.id = certificate_id
      and cand.claimed_by_profile_id = (select auth.uid())
  ) );

create policy "revocations_select_governance"
  on public.certificate_revocations for select to authenticated
  using (
    public.has_role('chairperson') or public.has_role('board_member') or public.has_role('chief_examiner')
  );

-- revocations: INSERT ---------------------------------------------------------
create policy "revocations_insert_examiner"
  on public.certificate_revocations for insert to authenticated
  with check ( public.has_role('examiner') and (select auth.uid()) = revoked_by_profile_id );

create policy "revocations_insert_governance"
  on public.certificate_revocations for insert to authenticated
  with check (
    public.has_role('chairperson') or public.has_role('board_member') or public.has_role('chief_examiner')
  );
-- (No UPDATE/DELETE: a revocation is a permanent fact.)


-- ----------------------------------------------------------------------------
-- Public verification — function, NOT a view.
--   Keyed by serial so the table can't be dumped/enumerated (protects minors).
--   Returns 0 or 1 rows. Masks the name if the candidate was anonymized.
-- ----------------------------------------------------------------------------
create or replace function public.verify_certificate(_serial text)
returns table (
  serial             text,
  level              public.badge_level,
  issued_on          date,
  center_name        text,
  candidate_name     text,
  is_valid           boolean,
  revoked_on         timestamptz,
  replaced_by_serial text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    c.serial,
    c.level,
    c.issued_on,
    pc.name,
    case when cand.status = 'anonymized'
         then '(record withdrawn)'
         else c.candidate_name_snapshot
    end                                   as candidate_name,
    (rev.id is null)                      as is_valid,
    rev.revoked_at                        as revoked_on,
    rep.serial                            as replaced_by_serial
  from public.certificates c
  left join public.partner_centers pc           on pc.id   = c.partner_center_id
  left join public.candidates cand              on cand.id = c.candidate_id
  left join public.certificate_revocations rev  on rev.certificate_id = c.id
  left join public.certificates rep             on rep.id  = rev.replaced_by_certificate_id
  where c.serial = _serial;
$$;

comment on function public.verify_certificate(text) is
  'Public, anonymous certificate check by exact serial. Lookup-only (no enumeration). Masks anonymized candidates.';

grant execute on function public.verify_certificate(text) to anon, authenticated;
